
export const MTS_BLUEPRINT = {
  examName: "MTS Exam",
  totalDurationMinutes: 60,
  parts: [
    {
      partName: "Part-A",
      totalMarks: 60,
      totalQuestions: 30,
      marksPerQuestion: 2,
      sections: [
        {
          sectionName: "Post Office Guide Part I",
          questionCount: 23,
          topics: [
            "Organization of the Department",
            "Type of Post Offices",
            "Business Hours",
            "Payment of postage, stamps and stationery",
            "General rules as to packing, sealing and posting, manner of affixing postage stamps",
            "Methods of address",
            "Post boxes and Post bags",
            "Duties of Letter Box peon",
            "Official postal articles",
            "Prohibited postal articles",
            "Products and Services: Mails, Banking & Remittances, Insurance, Stamps and Business (Reference: India Post website)",
          ],
        },
        {
          sectionName: "Postal Manual Volume V",
          questionCount: 7,
          topics: ["Definitions"],
        },
      ],
    },
    {
      partName: "Part-B",
      totalMarks: 40,
      totalQuestions: 20,
      marksPerQuestion: 2,
      sections: [
        {
          sectionName: "General Awareness/Knowledge",
          questionCount: 10,
          notes: "1 to 3 questions from each topic",
          topics: [
            "Indian Geography",
            "Indian Civics",
            "General knowledge",
            "Indian culture & freedom struggle",
            "Ethics and morale study",
            "Current Affairs",
          ],
        },
        {
          sectionName: "Basic Arithmetic",
          questionCount: 10,
          notes: "1 to 2 questions from each topic",
          topics: [
            "BODMAS",
            "Percentage",
            "Profit and loss",
            "Simple interest",
            "Average",
            "Time and work",
            "Time and distance",
            "Unitary method",
          ],
        },
      ],
    },
  ],
};

export const POSTMAN_BLUEPRINT = {
  examName: "Postman Exam",
  totalDurationMinutes: 90,
  parts: [
    {
      partName: "Part-A",
      totalMarks: 100,
      totalQuestions: 50,
      marksPerQuestion: 2,
      sections: [
        {
          sectionName: "Post Office Guide Part I",
          questionCount: 30,
          topics: [
            "Organization of the Department",
            "Type of Post Offices",
            "Business Hours",
            "Payment of postage, stamps and stationery",
            "General rules as to packing, sealing and posting, manner of affixing postage stamps",
            "Methods of address",
            "Post boxes and Post bags",
            "Delivery of mails",
            "Refusal of article",
            "Payment of eMoney Order",
            "Redirection",
            "Instruction regarding address change",
            "Articles addressed to deceased person",
            "Liability to detention to certain mails",
            "Facilities provided by Postmen in rural areas",
            "Products and Services: Mails, Banking & Remittances, Insurance, Stamps and Business (Reference: India Post Website)",
            "Prohibited postal Articles",
          ],
        },
        {
          sectionName: "Postal Manual Volume V",
          questionCount: 10,
          topics: [
            "Definitions: Head, Sub and Branch Office, Mail Bag, Face and Facing, Beat, Camp Correspondence, Late letters and too late letters, Mis-sent and Mis-directed articles",
          ],
        },
        {
          sectionName: "Postal Manual Volume VI - Part III",
          questionCount: 5,
          topics: [
            "Head Postman",
            "Knowledge of Postal Business",
            "Supply of forms to be carried out",
            "Sale of stamps",
            "Postman's Book",
            "Address to be noted on Postal Articles",
            "Damaged articles to be noticed",
            "Receipts for articles issued for delivery",
            "Book of receipts for intimations and notices delivery",
            "Instruction for delivery",
            "Realization of postage before delivery",
            "Receipts of addresses for registered",
            "Delivery to illiterate addressees, Pardanashin women",
            "Delivery of insured articles addressed to minors",
            "Payment of e-Money Orders",
            "e-Money Orders addressed to minors",
            "Payment of e-MO and delivery of registered letters to lunatics",
            "Duties of Village Postman",
          ],
        },
        {
          sectionName: "Postal Manual Vol. VII",
          questionCount: 5,
          topics: [
            "Stamps and Seals",
            "Portfolio and its contents",
            "Stationery",
            "Preparation of daily report",
            "Mail Abstract",
            "Exchange of Mails",
            "Cage TB",
            "Disposal of Mails addressed to a section or a mail office",
            "Closing of transit bags",
            "Duties and responsibilities of Mail Guard/Agent",
            "Final duties before quitting Van or office",
            "'A' order and 'B' order",
          ],
        },
      ],
    },
    {
      partName: "Part-B",
      totalMarks: 50,
      totalQuestions: 25,
      marksPerQuestion: 2,
      sections: [
        {
          sectionName: "General Awareness/Knowledge",
          questionCount: 10,
          notes: "1 to 3 questions from each topic",
          topics: [
            "Indian Geography",
            "Indian Civics",
            "General knowledge",
            "Indian culture & freedom struggle",
            "Ethics and morale study",
            "current affairs",
          ],
        },
        {
          sectionName: "Basic Arithmetic",
          questionCount: 10,
          notes: "1 to 2 questions from each topic",
          topics: [
            "BODMAS (brackets, orders, division, multiplication, addition, subtraction)",
            "Percentage",
            "Profit and loss",
            "Simple interest",
            "Average",
            "Time and work",
            "Time and distance",
            "Unitary method",
          ],
        },
        {
          sectionName: "Reasoning and Analytical Ability (Non Verbal / Pictorial)",
          questionCount: 5,
          topics: [],
        },
      ],
    },
  ],
};

export const PA_BLUEPRINT = {
  examName: "PA Exam",
  totalDurationMinutes: 120,
  parts: [
    {
      partName: "Part-A",
      totalMarks: 50,
      totalQuestions: 50,
      marksPerQuestion: 1,
      sections: [
        {
          sectionName: "Post Office Guide Part I (except Telegraphic Money Order)",
          questionCount: 10,
          topics: [],
        },
        {
          sectionName: "Post Office Guide Part II (except British and Irish Postal order)",
          questionCount: 10,
          topics: [],
        },
        {
          sectionName: "Basic terminologies related to IT Modernisation project of Department of Posts",
          questionCount: 10,
          topics: [],
        },
        {
          sectionName: "Products and Services: Mails, Banking & Remittances, Insurance, Stamps and Business (Reference: India Post Website)",
          questionCount: 10,
          topics: [],
        },
        {
          sectionName: "Combined Section: Postal Manuals and SB Orders",
          questionCount: 5,
          topics: [
            "Postal Manual Volume VI – Part I",
            "Postal Manual Volume VI – Part III (chapter I and II)",
            "Updated SB Orders issued by Directorate till 31st December of the preceding year in which exam is being conducted",
          ],
        },
        {
          sectionName: "Combined Section: Postal and Foreign Manuals",
          questionCount: 5,
          topics: ["Postal Manual Volume VII", "Foreign Post Manual"],
        },
      ],
    },
    {
      partName: "Part-B",
      totalMarks: 50,
      totalQuestions: 50,
      marksPerQuestion: 1,
      sections: [
        {
          sectionName: "General Awareness/Knowledge",
          questionCount: 10,
          notes: "2 questions from each topic",
          topics: [
            "Indian Geography",
            "Civics",
            "General knowledge",
            "Indian culture & freedom struggle",
            "Ethics and morale study",
            "current affairs",
          ],
        },
        {
          sectionName: "Basic Arithmetic",
          questionCount: 20,
          notes: "2 to 3 questions from each topic",
          topics: [
            "BODMAS (brackets, orders, division, multiplication, addition, subtraction)",
            "Percentage",
            "Profit and loss",
            "Simple interest",
            "Average",
            "Time and work",
            "Time and distance",
            "Unitary method",
          ],
        },
        {
          sectionName: "Reasoning and Analytical Ability (Non Verbal / Pictorial)",
          questionCount: 20,
          topics: [],
        },
      ],
    },
  ],
};
